{"name": "test_order_accept_wrong_courier_id_fail", "status": "passed", "description": "Акцепт заказа с неверным id курьера", "start": 1699369414850, "stop": 1699369415348, "uuid": "c3c1d1a2-faa2-443d-bbdb-4060caa51f35", "historyId": "b2f54e35f506157b9f87a073e6edd53e", "testCaseId": "b2f54e35f506157b9f87a073e6edd53e", "fullName": "tests.test_order.TestAcceptOrder#test_order_accept_wrong_courier_id_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "i101922157"}, {"name": "thread", "value": "18296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}