{"name": "test_courier_login_success", "status": "passed", "description": "Проверяем попытку входа с отправкой существующих данных", "start": 1699369349910, "stop": 1699369349992, "uuid": "691662dc-266f-4e8b-ae97-1ec7b33f4ba4", "historyId": "d0309d3f0e7911cef7e6fa887d1581d8", "testCaseId": "d0309d3f0e7911cef7e6fa887d1581d8", "fullName": "tests.test_courier.TestCourierLoginAPI#test_courier_login_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierLoginAPI"}, {"name": "host", "value": "i101922157"}, {"name": "thread", "value": "18296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}